### PR TITLE
Fixes and adds processes, updates docker container

### PR DESCRIPTION
**Pull request by Vlad-Dembrovskyi**
### Processes fixed:
- Three processes missed asort() function for awk, that is distrubuted
with GNU awk only. Solved by installing gawk to main siteqc container.

- Fourth process missed quotes around awk command and wrong output files
name.

### Processes added:
- `median_coverage_all` 
- `median_coverage_non_miss`
- `median_gq`
- `ab_ratio_p1` 
- `pull_1kg_p3_sites`
- `mend_err_p1`
- `mend_err_p2`
- `mend_dist`
- `mend_err_p3`
- `aggregate_annotation`

### Additionally:
- Updated docker container: added gawk and R libraries.
- Bound docker container to inherit for nfcore/base with an immutable tag.

### CODE REVIEW

**Comment by Vlad-Dembrovskyi** [comment]
The commit 441e1cd is successfully tested locally.
New container is uploaded to dockerhub, old container is preserved.
(each container tag contains the commit hash of this repo when container's dockerfile was updated)

### To test pipeline with this branch:
```
git clone https://github.com/lifebit-ai/siteqc
cd siteqc
git checkout vlad-dev1
nextflow run main.nf --input s3://lifebit-featured-datasets/projects/gel/siteqc/input.csv
```
### My result:
image

### New docker containers:
https://hub.docker.com/repository/docker/lifebitai/siteqc/tags?page=1
image

**Comment by Vlad-Dembrovskyi** [comment]
Additional --keep argument for `mend_err_p1` process has to be optional, I assume. So, in the default pipeline run with command written above the keep file is a blank file that is not added to the command at all. The example keep file is added to the project's s3 bucket and is available for the pipeline run.
**To test the pipeline including the example keep file run:** 
```
git clone https://github.com/lifebit-ai/siteqc
cd siteqc
git checkout vlad-dev1
nextflow run main.nf --input s3://lifebit-featured-datasets/projects/gel/siteqc/input.csv --triodata_keep_pheno s3://lifebit-featured-datasets/projects/gel/siteqc/keep.txt
```

**Comment by Vlad-Dembrovskyi** [comment]
image

**Comment by Vlad-Dembrovskyi** [comment]
Test after last commit: 
### The minimal viable pipeline is DONE
image

### Final aggregate annotation output file:
image


To reproduce pipeline run, the steps are same as before:
```
git clone https://github.com/lifebit-ai/siteqc
cd siteqc
git checkout vlad-dev1
nextflow run main.nf --input s3://lifebit-featured-datasets/projects/gel/siteqc/input.csv --triodata_keep_pheno s3://lifebit-featured-datasets/projects/gel/siteqc/keep.txt
```
(will run for ~3 min)
Also you can run with input2.csv instead of input.csv file. This has a second totally mocked file that gives empty final result, but shows that processess are parallelised correctly.
```
nextflow run main.nf --input s3://lifebit-featured-datasets/projects/gel/siteqc/input2.csv --triodata_keep_pheno s3://lifebit-featured-datasets/projects/gel/siteqc/keep.txt
```

**Review by cgpu — APPROVED** [review]
Looks good to me @Vlad-Dembrovskyi ! Squash it and for the newly groomed improvement use a new fresh branch.

**Pull request merged**
